### ISSUE TITLE
Texte dépassant les bords de la fenêtre

### ISSUE THREAD

**Issue by Feeling97** [Feeling97/t411ClientInstaller#2]
Sous certaines conditions, le texte dépasse la bordure de la fenêtre et certaines phrases sont donc incomplètes

Pour l'instant ce bug n'a été constaté que sous Linux : http://img15.hostingpics.net/pics/800998Screenshot23042015212128.png

**Comment by Namentis** [comment]
Bonjour, ce ticket étant encore ouvert je me permet de te conseiller d'utiliser QTextEdit au lieu des QtLabel. Ne me demande ni pourquoi ni comment je n'ai utilisé qu'une fois Qt et j'ai abandonné trop rapidement face à la difficultée ... ^^

Cela permettrait d'avoir apparemment de plus jolies zones de texte sous Qt. "setReadOnly(true);" empêcherai que l'on puisse écrire dans la zone (lecture seule).

A défaut te résoudre un problème je t'offre une piste !
Un peu de doc (en anglais) http://doc.qt.io/qt-4.8/qtextedit.html

En espérant t'avoir aidé et que tu n'ai pas déjà résolu le problème ou déjà vu cette solution qui n'a pas fonctionné. Je suis de très près ton topic bon courage pour l'avancée du projet !

Codialement,
Namentis

**Comment by Feeling97** [comment]
@Namentis Coucou, j'ai déjà tenté le QTextEdit, mais il ne me convient pas pour plusieurs choses:
- Il n'est pas fait pour ça (et j'aime avoir un code plutôt propre, même si c'est impossible qu'il le soit entièrement)
- Il ne me permet pas de formatter mes textes avec du HTML et du CSS
- Et il n'est pas fait pour ça (je fais une fixation là dessus :p )

Merci quand même d'avoir essayé de m'aider, et merci beaucoup pour tes encouragements!

**Comment by Namentis** [comment]
Re,

J'efface mon pavé pour aller un peu plus loin. Je vais faire quelques tests avec ton code. Aurais-tu plus d'informations par rapport à ton problème ? Afin de reproduire l'erreur.
- Distribution linux
- Version de la distribution
- Résolution de l'écran
- Version de Qt utilisé
  (pas simplement v4 ou + mais celle que tu utilises exactement)
- Autres qui pourraient m'être utile ...

Merci

Cordialement,
Namentis

**Comment by Feeling97** [comment]
J'ai aucune de ces infos :/ Faut voir avec la personne qui m'a reporté le bug, en fouillant dans le topic du forum tu devrais le retrouver (avec un screen du programme)
J'ai pas le temps de le faire là désolée :/

EDIT: J'ai trouvé, c'est TuxAnge qui m'avais fait remarquer ce bug, je vais lui en parler

**Comment by Namentis** [comment]
Très bien, je t'ai envoyé un message sur le forum (le premier est une erreur, le deuxième est là pour dire que le premier est une erreur), en attente des infos supp. !

**Comment by Feeling97** [comment]
Coucou @Namentis 
Comme tu peux le voir sur le forum, j'ai décidé de limiter le programme à Windows
Ce bug n'est donc plus d'actualité puisqu'il n'est constaté que sous Linux
Je ferme donc l'issue et je te remercie d'avoir pris du temps pour m'aider!
